---
title: "Accessibility Fails"
author: "Matthew Upson"
date: "23 August 2016"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  error = FALSE
  )

# Reproducibility stuff

library(checkpoint)
setSnapshot('2016-08-22')

# Load packages

library(dplyr)
library(readr)
library(digest)
library(magrittr)
library(ggplot2)
library(knitr)

# Load tools script

source('tools.R')
```

```{r}

fails_data <- 'accessibility_fail_data.csv' %>%
  read_csv %>%  
  dplyr::select(
    -WCAG_Level
  )


tool_names = names(fails_data)[-1]
names(tool_names) <- 1:length(tool_names)

argh <- function(x) {
  
  return(tool_names[x])
  
}

outcomes <- c('error_found','warning_reported','allows_manual_inspection')

```

```{r}

output <- 1:10 %>%
  purrr::map_df(
    ~ foobar(x = .x, outcomes[1]), 
    .id = "n_tools"
  ) %>%
  set_colnames(
    c('n_tools', 'score', 'tools')
  ) %>%
  tidyr::separate(
    tools,
    into = as.character(1:10)
  ) %>%
  as_data_frame %>%
  mutate_each(
    funs = funs(as.integer),
    3:12
  ) %>%
  mutate_each(
    funs = funs(argh),
    3:12
  )

output1 <- output %>%
  group_by(n_tools = as.integer(n_tools)) %>%
  dplyr::mutate(
    max = max(score)
  ) %>%
  dplyr::filter(
    score == max
    ) %>%
  select(-max)

output1 %>%
  kable

output1 %>%
  ggplot + 
  aes(
    x = n_tools,
    y = score,
    group = 1
  ) +
  geom_line() +
  xlab('Number of tools used') +
  ylab('Total number of fails identified') +
  scale_x_continuous(breaks = 1:10)  +
  ggtitle(paste(outcomes[1], collapse = ' + '))
```


```{r}

output <- 1:10 %>%
  purrr::map_df(
    ~ foobar(x = .x, outcomes[1:2]), 
    .id = "n_tools"
  ) %>%
  set_colnames(
    c('n_tools', 'score', 'tools')
  ) %>%
  tidyr::separate(
    tools,
    into = as.character(1:10)
  ) %>%
  as_data_frame %>%
  mutate_each(
    funs = funs(as.integer),
    3:12
  ) %>%
  mutate_each(
    funs = funs(argh),
    3:12
  )

output1 <- output %>%
  group_by(n_tools = as.integer(n_tools)) %>%
  dplyr::mutate(
    max = max(score)
  ) %>%
  dplyr::filter(
    score == max
    )  %>%
  select(-max)

output1 %>%
  kable

output1 %>%
  ggplot + 
  aes(
    x = n_tools,
    y = score,
    group = 1
  ) +
  geom_line() +
  xlab('Number of tools used') +
  ylab('Total number of fails identified') +
  scale_x_continuous(breaks = 1:10)  +
  ggtitle(paste(outcomes[1:2], collapse = ' + '))
```

```{r}

output <- 1:10 %>%
  purrr::map_df(
    ~ foobar(x = .x, outcomes[1:3]), 
    .id = "n_tools"
  ) %>%
  set_colnames(
    c('n_tools', 'score', 'tools')
  ) %>%
  tidyr::separate(
    tools,
    into = as.character(1:10)
  ) %>%
  as_data_frame %>%
  mutate_each(
    funs = funs(as.integer),
    3:12
  ) %>%
  mutate_each(
    funs = funs(argh),
    3:12
  )

output1 <- output %>%
  group_by(n_tools = as.integer(n_tools)) %>%
  dplyr::mutate(
    max = max(score)
  ) %>%
  dplyr::filter(
    score == max
    )  %>%
  select(-max)

output1 %>%
  kable

output1 %>%
  ggplot + 
  aes(
    x = n_tools,
    y = score,
    group = 1
  ) +
  geom_line() +
  xlab('Number of tools used') +
  ylab('Total number of fails identified') +
  scale_x_continuous(breaks = 1:10) +
  ggtitle(paste(outcomes[1:3], collapse = ' + '))
```